### ISSUE TITLE
Does not correctly disclaim warranty

### ISSUE THREAD

**Issue by chrisseaton** [GrenderG/Libcense-1.0#1]
I think this licence may not sufficiently disclaim warranty, as per the Uniform Commercial Code § 2-312 and § 1-201, and precedents set by test cases such as Kel-Keef Enterprises, Inc. v. Quality Components Corp.

People using this licence may be liable for warranty claims, even though the licence attempts to say that they would not be.

**Comment by GrenderG** [comment]
I have updated the `limitations` section, please check it.

**Comment by chrisseaton** [comment]
That seems like it would be more effective (I'm not a lawyer myself, I just knew the reason why other licences write the warranty bit differently).

If you haven't had a lawyer 'debug' your licence are you sure there are not more parts of it that look ok but are actually completely in effective, as this clause was?
